#!/usr/bin/env bash
# Regressions for node-version.sh (issue #275): the node train has a version of
# its own, held consistent across its two crates, and against the previous release
# it moves exactly when the node's inputs moved -- never left behind after a node
# change, never revved by a release that changed nothing the node is built from.
# shellcheck source=scripts/release/testlib.sh
source "$(dirname "$0")/testlib.sh"

sut="$RELEASE_DIR/node-version.sh"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# write_crate ROOT NAME VERSION-LINE DEPS... -> crates/NAME/Cargo.toml with src/lib.rs
# and a tests/ directory (which is not an input to the released binaries).
write_crate() {
  local root="$1" name="$2" version_line="$3"
  shift 3
  mkdir -p "$root/crates/$name/src" "$root/crates/$name/tests"
  {
    echo "[package]"
    echo "name = \"$name\""
    echo "$version_line"
    echo 'edition.workspace = true'
    echo
    echo "[dependencies]"
    printf '%s\n' "$@"
  } >"$root/crates/$name/Cargo.toml"
  echo "pub fn $(tr - _ <<<"$name")() {}" >"$root/crates/$name/src/lib.rs"
  echo "#[test] fn t() {}" >"$root/crates/$name/tests/t.rs"
}

# lock_package NAME VERSION [SOURCE CHECKSUM] DEPS... -> one [[package]] entry.
lock_package() {
  local name="$1" version="$2"
  shift 2
  echo "[[package]]"
  echo "name = \"$name\""
  echo "version = \"$version\""
  if [[ "${1:-}" == registry ]]; then
    echo 'source = "registry+https://github.com/rust-lang/crates.io-index"'
    echo "checksum = \"$2\""
    shift 2
  fi
  if [[ $# -gt 0 ]]; then
    echo "dependencies = ["
    printf ' "%s",\n' "$@"
    echo "]"
  fi
  echo
}

# write_lock ROOT [SERDE-CHECKSUM] [PROPTEST-CHECKSUM] -> Cargo.lock for the fixture
# workspace: serde and tempfile are in the node's closure, proptest is not.
write_lock() {
  local root="$1" serde="${2:-aaaa}" proptest="${3:-pppp}"
  {
    echo '# This file is automatically @generated by Cargo.'
    echo 'version = 4'
    echo
    lock_package proptest 1.5.0 registry "$proptest"
    lock_package serde 1.0.200 registry "$serde"
    lock_package tempfile 3.10.0 registry tttt
    lock_package ward-events "$WS_VERSION" serde
    lock_package ward-node "$NODE_VERSION" serde tempfile ward-events ward-node-protocol
    lock_package ward-node-client "$NODE_VERSION" serde ward-events ward-node ward-node-protocol
    lock_package ward-node-protocol "$WS_VERSION" serde ward-events
    lock_package ward-policy "$WS_VERSION" proptest serde
  } >"$root/Cargo.lock"
}

# write_workspace ROOT -> the root Cargo.toml.
write_workspace() {
  cat >"$1/Cargo.toml" <<TOML
[workspace]
resolver = "2"
members = [
    "crates/ward-events",
    "crates/ward-policy",
    "crates/ward-node-protocol",
    "crates/ward-node",
    "crates/ward-node-client",
]

[workspace.package]
version = "$WS_VERSION"
edition = "2024"

[profile.release]
lto = "thin"
TOML
}

# fresh_repo NAME -> a committed fixture repository tagged v1.0.0 with the node
# train at 0.1.0 and the workspace at 1.0.0; echoes its path.
fresh_repo() {
  local root="$work/$1"
  mkdir -p "$root"
  WS_VERSION=1.0.0 NODE_VERSION=0.1.0
  write_workspace "$root"
  write_crate "$root" ward-events 'version.workspace = true' 'serde = "1"'
  write_crate "$root" ward-policy 'version.workspace = true' 'serde = "1"' 'proptest = "1"'
  write_crate "$root" ward-node-protocol 'version.workspace = true' 'serde = "1"' \
    'ward-events = { path = "../ward-events", version = "1.0.0" }'
  write_crate "$root" ward-node 'version = "0.1.0"' 'serde = "1"' 'tempfile = "3"' \
    'ward-events = { path = "../ward-events", version = "1.0.0" }' \
    'ward-node-protocol = { path = "../ward-node-protocol", version = "1.0.0" }'
  write_crate "$root" ward-node-client 'version = "0.1.0"' 'serde = "1"' \
    'ward-events = { path = "../ward-events", version = "1.0.0" }' \
    'ward-node-protocol = { path = "../ward-node-protocol", version = "1.0.0" }' \
    '' '[dev-dependencies]' \
    'ward-node = { path = "../ward-node", version = "0.1.0" }'
  write_lock "$root"
  printf '[toolchain]\nchannel = "1.94.1"\n' >"$root/rust-toolchain.toml"
  (
    cd "$root" || exit 1
    git init -q
    git -c user.name=t -c user.email=t@t add -A
    git -c user.name=t -c user.email=t@t commit -q -m "release 1.0.0"
    git tag v1.0.0
  )
  printf '%s' "$root"
}

# set_node_version ROOT VERSION -> both node crates and the requirement on ward-node.
set_node_version() {
  local root="$1" v="$2"
  sed -i "s/^version = \"0\.1\.0\"/version = \"$v\"/" "$root/crates/ward-node/Cargo.toml" "$root/crates/ward-node-client/Cargo.toml"
  sed -i "s/version = \"0\.1\.0\" }/version = \"$v\" }/" "$root/crates/ward-node-client/Cargo.toml"
  NODE_VERSION="$v" WS_VERSION=1.0.0 write_lock "$root"
}

### Consistency ##################################################################

r="$(fresh_repo consistent)"
out="$(bash "$sut" --root "$r")" || fail "consistent: refused"
[[ "$out" == "0.1.0" ]] || fail "consistent: printed '$out', not the node version"
echo "ok   a consistent node train prints its version"

r="$(fresh_repo inherits-workspace)"
sed -i 's/^version = "0.1.0"/version.workspace = true/' "$r/crates/ward-node/Cargo.toml"
expect_status 1 "a node crate inheriting the workspace version is refused" bash "$sut" --root "$r"

r="$(fresh_repo crates-disagree)"
sed -i 's/^version = "0.1.0"/version = "0.2.0"/' "$r/crates/ward-node-client/Cargo.toml"
expect_status 2 "node crates with different versions are refused" bash "$sut" --root "$r"

r="$(fresh_repo requirement-stale)"
sed -i 's/version = "0.1.0" }/version = "0.0.9" }/' "$r/crates/ward-node-client/Cargo.toml"
expect_status 2 "a path requirement on a node crate at another version is refused" bash "$sut" --root "$r"

r="$(fresh_repo not-semver)"
sed -i 's/^version = "0.1.0"/version = "01.2"/' "$r/crates/ward-node/Cargo.toml" "$r/crates/ward-node-client/Cargo.toml"
expect_status 1 "a node version that is not SemVer is refused" bash "$sut" --root "$r"

expect_status 1 "a root without a workspace manifest is refused" bash "$sut" --root "$work/does-not-exist"

### Against the previous release #################################################

r="$(fresh_repo unchanged-same)"
echo "# release notes" >"$r/CHANGELOG.md"
# What a release PR does: the workspace version and every path requirement on a
# workspace-versioned crate move, in the node crates' manifests too.
sed -i 's/^version = "1.0.0"/version = "1.1.0"/' "$r/Cargo.toml"
sed -i 's/version = "1.0.0" }/version = "1.1.0" }/' "$r"/crates/*/Cargo.toml
WS_VERSION=1.1.0 NODE_VERSION=0.1.0 write_lock "$r"
out="$(bash "$sut" --root "$r" --since v1.0.0)" || fail "unchanged-same: refused"
[[ "$out" == "0.1.0" ]] || fail "unchanged-same: printed '$out'"
echo "ok   a release that changed nothing the node is built from keeps the node version"

r="$(fresh_repo unchanged-bumped)"
set_node_version "$r" 0.2.0
expect_status 4 "a node version bump with no node change is refused" bash "$sut" --root "$r" --since v1.0.0

r="$(fresh_repo node-src-same)"
echo "pub fn more() {}" >>"$r/crates/ward-node/src/lib.rs"
expect_status 3 "a node source change without a version bump is refused" bash "$sut" --root "$r" --since v1.0.0

r="$(fresh_repo node-src-bumped)"
echo "pub fn more() {}" >>"$r/crates/ward-node/src/lib.rs"
set_node_version "$r" 0.1.1
out="$(bash "$sut" --root "$r" --since v1.0.0)" || fail "node-src-bumped: refused"
[[ "$out" == "0.1.1" ]] || fail "node-src-bumped: printed '$out'"
echo "ok   a node change with a higher node version passes"

r="$(fresh_repo node-src-lowered)"
echo "pub fn more() {}" >>"$r/crates/ward-node/src/lib.rs"
set_node_version "$r" 0.0.9
expect_status 5 "a node change with a lower node version is refused" bash "$sut" --root "$r" --since v1.0.0

r="$(fresh_repo node-manifest-same)"
echo 'nix = "0.30"' >>"$r/crates/ward-node/Cargo.toml"
expect_status 3 "a node manifest change beyond its versions counts" bash "$sut" --root "$r" --since v1.0.0

r="$(fresh_repo adapter-src-same)"
echo "pub fn more() {}" >>"$r/crates/ward-node-client/src/lib.rs"
expect_status 3 "a change to the adapter crate counts as a node change" bash "$sut" --root "$r" --since v1.0.0

r="$(fresh_repo shared-dep-same)"
echo "pub fn more() {}" >>"$r/crates/ward-events/src/lib.rs"
expect_status 3 "a change to a workspace crate the node depends on counts" bash "$sut" --root "$r" --since v1.0.0

r="$(fresh_repo unrelated-crate)"
echo "pub fn more() {}" >>"$r/crates/ward-policy/src/lib.rs"
expect_status 0 "a change to a workspace crate outside the node's closure does not count" bash "$sut" --root "$r" --since v1.0.0

r="$(fresh_repo tests-only)"
echo "#[test] fn u() {}" >>"$r/crates/ward-node/tests/t.rs"
expect_status 0 "a change under a node crate's tests/ does not count" bash "$sut" --root "$r" --since v1.0.0

r="$(fresh_repo locked-dep-in-closure)"
WS_VERSION=1.0.0 NODE_VERSION=0.1.0 write_lock "$r" bbbb
expect_status 3 "a locked dependency of the node changing counts" bash "$sut" --root "$r" --since v1.0.0

r="$(fresh_repo locked-dep-outside-closure)"
WS_VERSION=1.0.0 NODE_VERSION=0.1.0 write_lock "$r" aaaa qqqq
expect_status 0 "a locked dependency outside the node's closure does not count" bash "$sut" --root "$r" --since v1.0.0

r="$(fresh_repo toolchain)"
printf '[toolchain]\nchannel = "1.95.0"\n' >"$r/rust-toolchain.toml"
expect_status 3 "a toolchain change counts" bash "$sut" --root "$r" --since v1.0.0

r="$(fresh_repo profile)"
sed -i 's/^lto = "thin"/lto = "fat"/' "$r/Cargo.toml"
expect_status 3 "a release profile change counts" bash "$sut" --root "$r" --since v1.0.0

# What changed is said, so the release log explains the refusal.
r="$(fresh_repo reasons)"
echo "pub fn more() {}" >>"$r/crates/ward-events/src/lib.rs"
printf '[toolchain]\nchannel = "1.95.0"\n' >"$r/rust-toolchain.toml"
err="$(bash "$sut" --root "$r" --since v1.0.0 2>&1 >/dev/null || true)"
grep -q 'ward-events' <<<"$err" || fail "reasons: the changed crate is not named"
grep -q 'rust-toolchain.toml' <<<"$err" || fail "reasons: the toolchain is not named"
echo "ok   the refusal names what changed"

### The previous release had no node train #######################################

r="$(fresh_repo first-node-release)"
(
  cd "$r" || exit 1
  git -c user.name=t -c user.email=t@t rm -q -r crates/ward-node crates/ward-node-client
  sed -i '/ward-node"/d; /ward-node-client"/d' Cargo.toml
  git -c user.name=t -c user.email=t@t commit -q -am "before the node existed"
  git tag v0.9.0
)
# Back on a tree that has the node.
(cd "$r" && git checkout -q v1.0.0 -- . && git -c user.name=t -c user.email=t@t commit -q -am "the node" )
out="$(bash "$sut" --root "$r" --since v0.9.0)" || fail "first-node-release: refused"
[[ "$out" == "0.1.0" ]] || fail "first-node-release: printed '$out'"
echo "ok   a previous release without the node train accepts any valid node version"

# The previous release's node crate inherited the workspace version: that version is
# the one the node then shipped under, and the comparison is against it.
r="$(fresh_repo previously-inherited)"
(
  cd "$r" || exit 1
  sed -i 's/^version = "0.1.0"/version.workspace = true/' crates/ward-node/Cargo.toml crates/ward-node-client/Cargo.toml
  sed -i 's/version = "0.1.0" }/version = "1.0.0" }/' crates/ward-node-client/Cargo.toml
  NODE_VERSION=1.0.0 WS_VERSION=1.0.0 write_lock .
  git -c user.name=t -c user.email=t@t commit -q -am "node under the workspace version"
  git tag v1.0.1
  git checkout -q v1.0.0 -- . && git -c user.name=t -c user.email=t@t commit -q -am "node train on its own"
)
expect_status 4 "taking the node off the workspace version without a node change is refused" bash "$sut" --root "$r" --since v1.0.1
echo "pub fn more() {}" >>"$r/crates/ward-node/src/lib.rs"
expect_status 5 "a node version below the one the previous release shipped under is refused" bash "$sut" --root "$r" --since v1.0.1
set_node_version "$r" 1.0.2
expect_status 0 "a node version above the one the previous release shipped under passes" bash "$sut" --root "$r" --since v1.0.1

### Guardrails ##################################################################

r="$(fresh_repo unknown-ref)"
expect_status 1 "an unknown previous release ref is refused" bash "$sut" --root "$r" --since v9.9.9
expect_status 1 "an unknown option is refused" bash "$sut" --root "$r" --bogus

echo "PASS node-version.test.sh"
