#!/usr/bin/env bash
# Turn a built WardOS image into a bootable disk with bootc-image-builder.
#
#   image/disk.sh --type qcow2|iso [--image NAME] [--output DIR] [--rootfs FS]
#                 [--user NAME [--password PW] [--ssh-key FILE]] [--luks]
#                 [--config FILE] [--dry-run]
#
# Defaults: image localhost/wardos:<git describe --tags --always>, output ./image/out,
# rootfs btrfs (ADR-0001). --user writes a bootc-image-builder config that creates the
# first user (wheel; the desktop's autologin expects `wardos`) with --password (or
# WARDOS_PASSWORD in the environment, which keeps it out of `ps`) and/or --ssh-key.
# --luks (iso only) asks Anaconda for full-disk encryption through a kickstart, the
# passphrase typed at install time. --config passes your own TOML instead. Must run as
# root: the builder is a privileged container that reads root's container storage and
# writes the disk image. See image/README.md, "Users and LUKS".
set -euo pipefail

usage() {
  sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'
}

repo_root=$(cd "$(dirname "$0")/.." && pwd)
cd "$repo_root"

podman_bin=${PODMAN:-podman}
# Pinned builder image; bump deliberately (image/README.md, "bootc-image-builder").
builder=${BOOTC_IMAGE_BUILDER:-quay.io/centos-bootc/bootc-image-builder:latest}
type=""
image=""
output="$repo_root/image/out"
rootfs="btrfs"
config=""
user=""
password=${WARDOS_PASSWORD:-}
ssh_key=""
luks=0
dry_run=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --type) type=$2; shift 2 ;;
    --type=*) type=${1#--type=}; shift ;;
    --image) image=$2; shift 2 ;;
    --image=*) image=${1#--image=}; shift ;;
    --output) output=$2; shift 2 ;;
    --output=*) output=${1#--output=}; shift ;;
    --rootfs) rootfs=$2; shift 2 ;;
    --rootfs=*) rootfs=${1#--rootfs=}; shift ;;
    --config) config=$2; shift 2 ;;
    --config=*) config=${1#--config=}; shift ;;
    --user) user=$2; shift 2 ;;
    --user=*) user=${1#--user=}; shift ;;
    --password) password=$2; shift 2 ;;
    --password=*) password=${1#--password=}; shift ;;
    --ssh-key) ssh_key=$2; shift 2 ;;
    --ssh-key=*) ssh_key=${1#--ssh-key=}; shift ;;
    --luks) luks=1; shift ;;
    --dry-run) dry_run=1; shift ;;
    -h | --help) usage; exit 0 ;;
    *) echo "disk.sh: unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

case "$type" in
  qcow2 | iso) ;;
  "") echo "disk.sh: --type qcow2|iso is required" >&2; exit 2 ;;
  *) echo "disk.sh: unsupported --type '$type' (qcow2 or iso)" >&2; exit 2 ;;
esac

if [[ -z "$image" ]]; then
  image="localhost/wardos:$(git describe --tags --always 2>/dev/null || echo dev)"
fi

if [[ -n "$config" && ! -f "$config" ]]; then
  echo "disk.sh: config file not found: $config" >&2
  exit 1
fi
if [[ -n "$config" && ( -n "$user" || $luks -eq 1 ) ]]; then
  echo "disk.sh: --config carries its own users and partitioning; drop it or drop --user/--luks" >&2
  exit 2
fi
if [[ -n "$ssh_key" && ! -f "$ssh_key" ]]; then
  echo "disk.sh: ssh key file not found: $ssh_key" >&2
  exit 1
fi
if [[ -n "$user" && -z "$password" && -z "$ssh_key" ]]; then
  echo "disk.sh: --user needs --password (or WARDOS_PASSWORD) or --ssh-key, or nobody can use sudo" >&2
  exit 2
fi
if [[ $luks -eq 1 && "$type" != iso ]]; then
  # The bootc-image-builder blueprint knows plain, lvm and btrfs partitions and nothing
  # encrypted; disk encryption is Anaconda's job, so it is only reachable through the
  # installer ISO's kickstart.
  echo "disk.sh: --luks needs --type iso (bootc-image-builder cannot encrypt a qcow2; the installer can)" >&2
  exit 2
fi

# --- the generated bootc-image-builder config -------------------------------------------
# bootc-image-builder refuses [[customizations.user]] next to a custom kickstart, so with
# --luks the user is a kickstart `user` line instead; without it, the builder's own user
# customization does the same job on both output types.
write_config() {
  local key=""
  if [[ -n "$ssh_key" ]]; then key=$(<"$ssh_key"); fi
  echo "# Generated by image/disk.sh; do not commit (it may hold a password)."
  if [[ $luks -eq 1 ]]; then
    echo "[customizations.installer.kickstart]"
    echo 'contents = """'
    echo "# Full-disk encryption: autopart --encrypted without --passphrase makes Anaconda"
    echo "# ask for one during the installation (unverified until E-09)."
    echo "zerombr"
    echo "clearpart --all --initlabel --disklabel=gpt"
    echo "autopart --noswap --type=${rootfs} --encrypted"
    echo "network --bootproto=dhcp --device=link --activate --onboot=on"
    echo "lang en_US.UTF-8"
    echo "keyboard us"
    echo "timezone UTC --utc"
    echo "rootpw --lock"
    if [[ -n "$user" ]]; then
      local line="user --name=${user} --groups=wheel"
      if [[ -n "$password" ]]; then line+=" --password=${password} --plaintext"; fi
      echo "$line"
      if [[ -n "$key" ]]; then echo "sshkey --username=${user} \"${key}\""; fi
    fi
    echo "reboot"
    echo '"""'
  elif [[ -n "$user" ]]; then
    echo "[[customizations.user]]"
    echo "name = \"${user}\""
    if [[ -n "$password" ]]; then echo "password = \"${password}\""; fi
    if [[ -n "$key" ]]; then echo "key = \"${key}\""; fi
    echo 'groups = ["wheel"]'
  fi
}

generated=""
if [[ -n "$user" || $luks -eq 1 ]]; then
  mkdir -p "$output"
  generated="$output/config.toml"
  (umask 077 && write_config >"$generated")
  config=$generated
fi

# A terminal only when there is one: CI has no tty, and podman refuses -t without it.
tty_flag=()
if [[ -t 0 ]]; then tty_flag=(-t); fi
cmd=("$podman_bin" run --rm -i "${tty_flag[@]}"
  --privileged
  --security-opt label=type:unconfined_t
  --volume "${output}:/output"
  --volume /var/lib/containers/storage:/var/lib/containers/storage)
if [[ -n "$config" ]]; then
  cmd+=(--volume "$(realpath "$config"):/config.toml:ro")
fi
cmd+=("$builder"
  --type "$type"
  --rootfs "$rootfs")
if [[ -n "$config" ]]; then
  cmd+=(--config /config.toml)
fi
cmd+=("$image")

printf 'disk.sh: would run (output in %s):\n  mkdir -p %q\n  ' "$output" "$output"
printf '%q ' "${cmd[@]}"
printf '\n'
if [[ -n "$generated" ]]; then
  echo "disk.sh: wrote $generated (mode 0600):"
  # Never echo the password; the file has it.
  (password='********' && write_config) | sed 's/^/  /'
fi

if [[ $dry_run -eq 1 ]]; then
  exit 0
fi

if ! command -v "$podman_bin" >/dev/null 2>&1; then
  echo "disk.sh: $podman_bin is not installed; install podman or re-run with --dry-run" >&2
  exit 1
fi
if [[ $EUID -ne 0 ]]; then
  echo "disk.sh: bootc-image-builder needs root (sudo $0 ...)" >&2
  exit 1
fi
if ! "$podman_bin" image exists "$image"; then
  # A registry reference (ghcr.io/hexrift/wardos:latest, the image CI publishes on
  # every merge) is pulled; a local name has to come from image/build.sh.
  if [[ "$image" == */*.*/* || "$image" == ghcr.io/* ]]; then
    echo "disk.sh: pulling $image"
    "$podman_bin" pull "$image"
  else
    echo "disk.sh: image $image is not in root's container storage; run sudo image/build.sh first" >&2
    exit 1
  fi
fi

mkdir -p "$output"
exec "${cmd[@]}"
